/* The following code was generated by JFlex 1.4.3 on 22/01/13 16:11 */

/* === USERCODE SECTION === */

package pl.edu.agh.codecomp.jflex;

/* JFlex example */

import java_cup.runtime.*;

/**
* This class is a test lexer
*/

public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int NESTED_COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\16\0\4\0\1\3\1\0"+
    "\1\21\1\0\1\0\2\0\1\30\2\0\1\4\1\23\1\25\1\0"+
    "\1\24\1\5\1\6\11\7\1\27\1\26\1\0\1\22\3\0\32\0"+
    "\1\0\1\31\2\0\1\0\1\0\1\10\1\15\1\13\1\14\4\0"+
    "\1\20\2\0\1\11\1\0\1\33\1\0\1\17\1\0\1\34\1\16"+
    "\1\32\3\0\1\12\2\0\4\0\41\0\2\0\4\0\4\0\1\0"+
    "\2\0\1\0\7\0\1\0\4\0\1\0\5\0\27\0\1\0\37\0"+
    "\1\0\u01ca\0\4\0\14\0\16\0\5\0\7\0\1\0\1\0\1\0"+
    "\21\0\160\0\5\0\1\0\2\0\2\0\4\0\10\0\1\0\1\0"+
    "\3\0\1\0\1\0\1\0\24\0\1\0\123\0\1\0\213\0\1\0"+
    "\5\0\2\0\236\0\11\0\46\0\2\0\1\0\7\0\47\0\11\0"+
    "\55\0\1\0\1\0\1\0\2\0\1\0\2\0\1\0\1\0\10\0"+
    "\33\0\5\0\3\0\15\0\4\0\7\0\1\0\4\0\13\0\5\0"+
    "\53\0\37\0\4\0\2\0\1\0\143\0\1\0\1\0\10\0\1\0"+
    "\6\0\2\0\2\0\1\0\4\0\2\0\12\0\3\0\2\0\1\0"+
    "\17\0\1\0\1\0\1\0\36\0\33\0\2\0\131\0\13\0\1\0"+
    "\16\0\12\0\41\0\11\0\2\0\4\0\1\0\5\0\26\0\4\0"+
    "\1\0\11\0\1\0\3\0\1\0\5\0\22\0\31\0\3\0\244\0"+
    "\4\0\66\0\3\0\1\0\22\0\1\0\7\0\12\0\2\0\2\0"+
    "\12\0\1\0\7\0\1\0\7\0\1\0\3\0\1\0\10\0\2\0"+
    "\2\0\2\0\26\0\1\0\7\0\1\0\1\0\3\0\4\0\2\0"+
    "\1\0\1\0\7\0\2\0\2\0\2\0\3\0\1\0\10\0\1\0"+
    "\4\0\2\0\1\0\3\0\2\0\2\0\12\0\4\0\7\0\1\0"+
    "\5\0\3\0\1\0\6\0\4\0\2\0\2\0\26\0\1\0\7\0"+
    "\1\0\2\0\1\0\2\0\1\0\2\0\2\0\1\0\1\0\5\0"+
    "\4\0\2\0\2\0\3\0\3\0\1\0\7\0\4\0\1\0\1\0"+
    "\7\0\14\0\3\0\1\0\13\0\3\0\1\0\11\0\1\0\3\0"+
    "\1\0\26\0\1\0\7\0\1\0\2\0\1\0\5\0\2\0\1\0"+
    "\1\0\10\0\1\0\3\0\1\0\3\0\2\0\1\0\17\0\2\0"+
    "\2\0\2\0\12\0\1\0\1\0\17\0\3\0\1\0\10\0\2\0"+
    "\2\0\2\0\26\0\1\0\7\0\1\0\2\0\1\0\5\0\2\0"+
    "\1\0\1\0\7\0\2\0\2\0\2\0\3\0\10\0\2\0\4\0"+
    "\2\0\1\0\3\0\2\0\2\0\12\0\1\0\1\0\20\0\1\0"+
    "\1\0\1\0\6\0\3\0\3\0\1\0\4\0\3\0\2\0\1\0"+
    "\1\0\1\0\2\0\3\0\2\0\3\0\3\0\3\0\14\0\4\0"+
    "\5\0\3\0\3\0\1\0\4\0\2\0\1\0\6\0\1\0\16\0"+
    "\12\0\11\0\1\0\7\0\3\0\1\0\10\0\1\0\3\0\1\0"+
    "\27\0\1\0\12\0\1\0\5\0\3\0\1\0\7\0\1\0\3\0"+
    "\1\0\4\0\7\0\2\0\1\0\2\0\6\0\2\0\2\0\2\0"+
    "\12\0\22\0\2\0\1\0\10\0\1\0\3\0\1\0\27\0\1\0"+
    "\12\0\1\0\5\0\2\0\1\0\1\0\7\0\1\0\3\0\1\0"+
    "\4\0\7\0\2\0\7\0\1\0\1\0\2\0\2\0\2\0\12\0"+
    "\1\0\2\0\17\0\2\0\1\0\10\0\1\0\3\0\1\0\51\0"+
    "\2\0\1\0\7\0\1\0\3\0\1\0\4\0\1\0\10\0\1\0"+
    "\10\0\2\0\2\0\2\0\12\0\12\0\6\0\2\0\2\0\1\0"+
    "\22\0\3\0\30\0\1\0\11\0\1\0\1\0\2\0\7\0\3\0"+
    "\1\0\4\0\6\0\1\0\1\0\1\0\10\0\22\0\2\0\15\0"+
    "\60\0\1\0\2\0\7\0\4\0\10\0\10\0\1\0\12\0\47\0"+
    "\2\0\1\0\1\0\2\0\2\0\1\0\1\0\2\0\1\0\6\0"+
    "\4\0\1\0\7\0\1\0\3\0\1\0\1\0\1\0\1\0\2\0"+
    "\2\0\1\0\4\0\1\0\2\0\6\0\1\0\2\0\1\0\2\0"+
    "\5\0\1\0\1\0\1\0\6\0\2\0\12\0\2\0\2\0\42\0"+
    "\1\0\27\0\2\0\6\0\12\0\13\0\1\0\1\0\1\0\1\0"+
    "\1\0\4\0\2\0\10\0\1\0\44\0\4\0\24\0\1\0\2\0"+
    "\5\0\13\0\1\0\44\0\11\0\1\0\71\0\53\0\24\0\1\0"+
    "\12\0\6\0\6\0\4\0\4\0\3\0\1\0\3\0\2\0\7\0"+
    "\3\0\4\0\15\0\14\0\1\0\17\0\2\0\46\0\12\0\53\0"+
    "\1\0\1\0\3\0\u0149\0\1\0\4\0\2\0\7\0\1\0\1\0"+
    "\1\0\4\0\2\0\51\0\1\0\4\0\2\0\41\0\1\0\4\0"+
    "\2\0\7\0\1\0\1\0\1\0\4\0\2\0\17\0\1\0\71\0"+
    "\1\0\4\0\2\0\103\0\2\0\3\0\40\0\20\0\20\0\125\0"+
    "\14\0\u026c\0\2\0\21\0\1\0\32\0\5\0\113\0\3\0\3\0"+
    "\17\0\15\0\1\0\4\0\3\0\13\0\22\0\3\0\13\0\22\0"+
    "\2\0\14\0\15\0\1\0\3\0\1\0\2\0\14\0\64\0\40\0"+
    "\3\0\1\0\3\0\2\0\1\0\2\0\12\0\41\0\3\0\2\0"+
    "\12\0\6\0\130\0\10\0\51\0\1\0\1\0\5\0\106\0\12\0"+
    "\35\0\3\0\14\0\4\0\14\0\12\0\12\0\36\0\2\0\5\0"+
    "\13\0\54\0\4\0\21\0\7\0\2\0\6\0\12\0\46\0\27\0"+
    "\5\0\4\0\65\0\12\0\1\0\35\0\2\0\13\0\6\0\12\0"+
    "\15\0\1\0\130\0\5\0\57\0\21\0\7\0\4\0\12\0\21\0"+
    "\11\0\14\0\3\0\36\0\12\0\3\0\2\0\12\0\6\0\46\0"+
    "\16\0\14\0\44\0\24\0\10\0\12\0\3\0\3\0\12\0\44\0"+
    "\122\0\3\0\1\0\25\0\4\0\1\0\4\0\1\0\15\0\300\0"+
    "\47\0\25\0\4\0\u0116\0\2\0\6\0\2\0\46\0\2\0\6\0"+
    "\2\0\10\0\1\0\1\0\1\0\1\0\1\0\1\0\1\0\37\0"+
    "\2\0\65\0\1\0\7\0\1\0\1\0\3\0\3\0\1\0\7\0"+
    "\3\0\4\0\2\0\6\0\4\0\15\0\5\0\3\0\1\0\7\0"+
    "\16\0\5\0\32\0\5\0\20\0\2\0\23\0\1\0\13\0\5\0"+
    "\5\0\6\0\1\0\1\0\15\0\1\0\20\0\15\0\3\0\32\0"+
    "\26\0\15\0\4\0\1\0\3\0\14\0\21\0\1\0\4\0\1\0"+
    "\2\0\12\0\1\0\1\0\3\0\5\0\6\0\1\0\1\0\1\0"+
    "\1\0\1\0\1\0\4\0\1\0\13\0\2\0\4\0\5\0\5\0"+
    "\4\0\1\0\21\0\51\0\u0a77\0\57\0\1\0\57\0\1\0\205\0"+
    "\6\0\4\0\3\0\16\0\46\0\12\0\66\0\11\0\1\0\17\0"+
    "\1\0\27\0\11\0\7\0\1\0\7\0\1\0\7\0\1\0\7\0"+
    "\1\0\7\0\1\0\7\0\1\0\7\0\1\0\7\0\1\0\40\0"+
    "\57\0\1\0\u01d5\0\3\0\31\0\11\0\6\0\1\0\5\0\2\0"+
    "\5\0\4\0\126\0\2\0\2\0\2\0\3\0\1\0\132\0\1\0"+
    "\4\0\5\0\51\0\3\0\136\0\21\0\33\0\65\0\20\0\u0200\0"+
    "\u19b6\0\112\0\u51cc\0\64\0\u048d\0\103\0\56\0\2\0\u010d\0\3\0"+
    "\20\0\12\0\2\0\24\0\57\0\1\0\14\0\2\0\1\0\31\0"+
    "\10\0\120\0\2\0\45\0\11\0\2\0\147\0\2\0\4\0\1\0"+
    "\2\0\16\0\12\0\120\0\10\0\1\0\3\0\1\0\4\0\1\0"+
    "\27\0\5\0\20\0\1\0\7\0\64\0\14\0\2\0\62\0\21\0"+
    "\13\0\12\0\6\0\22\0\6\0\3\0\1\0\4\0\12\0\34\0"+
    "\10\0\2\0\27\0\15\0\14\0\35\0\3\0\4\0\57\0\16\0"+
    "\16\0\1\0\12\0\46\0\51\0\16\0\11\0\3\0\1\0\10\0"+
    "\2\0\2\0\12\0\6\0\27\0\3\0\1\0\1\0\4\0\60\0"+
    "\1\0\1\0\3\0\2\0\2\0\5\0\2\0\1\0\1\0\1\0"+
    "\30\0\3\0\43\0\6\0\2\0\6\0\2\0\6\0\11\0\7\0"+
    "\1\0\7\0\221\0\43\0\10\0\1\0\2\0\2\0\12\0\6\0"+
    "\u2ba4\0\14\0\27\0\4\0\61\0\u2104\0\u012e\0\2\0\76\0\2\0"+
    "\152\0\46\0\7\0\14\0\5\0\5\0\1\0\1\0\12\0\1\0"+
    "\15\0\1\0\5\0\1\0\1\0\1\0\2\0\1\0\2\0\1\0"+
    "\154\0\41\0\u016b\0\22\0\100\0\2\0\66\0\50\0\15\0\3\0"+
    "\20\0\20\0\7\0\14\0\2\0\30\0\3\0\31\0\1\0\6\0"+
    "\5\0\1\0\207\0\2\0\1\0\4\0\1\0\13\0\12\0\7\0"+
    "\32\0\4\0\1\0\1\0\32\0\13\0\131\0\3\0\6\0\2\0"+
    "\6\0\2\0\6\0\2\0\3\0\3\0\2\0\3\0\2\0\22\0"+
    "\3\0\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\1\2\3\5\1\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\2\14\1\15"+
    "\2\0\1\16\1\17\1\20\1\21\1\22\1\23\3\0"+
    "\1\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[37];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\35\0\72\0\72\0\127\0\72\0\164\0\72"+
    "\0\221\0\256\0\313\0\350\0\u0105\0\u0122\0\72\0\u013f"+
    "\0\72\0\72\0\72\0\72\0\72\0\u015c\0\72\0\u015c"+
    "\0\u0179\0\u0196\0\u01b3\0\72\0\72\0\72\0\72\0\72"+
    "\0\72\0\u01d0\0\u01ed\0\u020a\0\u01d0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[37];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\4\1\7\1\10\1\11\1\12"+
    "\2\4\1\13\1\14\1\15\1\16\2\4\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\5\4\1\26\2\0"+
    "\16\26\1\27\6\26\1\30\1\31\3\26\37\0\1\6"+
    "\36\0\1\32\1\33\35\0\2\11\36\0\2\34\34\0"+
    "\1\34\34\0\1\34\5\0\1\34\26\0\1\34\4\0"+
    "\1\34\34\0\2\34\36\0\1\35\12\0\1\26\2\0"+
    "\16\26\1\0\7\26\1\0\3\26\21\0\1\36\10\0"+
    "\1\37\1\40\1\41\4\42\1\43\30\42\1\33\1\5"+
    "\1\6\32\33\4\42\1\44\34\42\1\44\1\45\33\42"+
    "\1\44\1\6\27\42";

  private static int [] zzUnpackTrans() {
    int [] result = new int[551];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\10\1\11\1\1\1\11\1\1\1\11\6\1"+
    "\1\11\1\1\5\11\1\1\1\11\2\1\2\0\6\11"+
    "\3\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[37];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

StringBuffer string = new StringBuffer();

private Symbol symbol(int type) {
	return new Symbol(type, yyline, yycolumn);
}

private Symbol symbol(int type, Object value) {
	return new Symbol(type, yyline, yycolumn, value);
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2184) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 18: 
          { string.append('\n');
          }
        case 20: break;
        case 15: 
          { return symbol(2);
          }
        case 21: break;
        case 7: 
          { return symbol(4);
          }
        case 22: break;
        case 9: 
          { return symbol(6);
          }
        case 23: break;
        case 13: 
          { string.append('\\');
          }
        case 24: break;
        case 14: 
          { return symbol(666);
          }
        case 25: break;
        case 4: 
          { string.setLength(0); yybegin(STRING);
          }
        case 26: break;
        case 5: 
          { return symbol(1);
          }
        case 27: break;
        case 6: 
          { return symbol(3);
          }
        case 28: break;
        case 19: 
          { string.append('\r');
          }
        case 29: break;
        case 11: 
          { string.append(yytext());
          }
        case 30: break;
        case 8: 
          { return symbol(5);
          }
        case 31: break;
        case 3: 
          { return symbol(sym.INTEGER_LITERAL);
          }
        case 32: break;
        case 16: 
          { string.append('\"');
          }
        case 33: break;
        case 10: 
          { return symbol(7);
          }
        case 34: break;
        case 12: 
          { yybegin(YYINITIAL);
						  return symbol(sym.LITERAL.STRING, string.toString());
          }
        case 35: break;
        case 1: 
          { throw new Error("Illegal character <"+ yytext() +">");
          }
        case 36: break;
        case 2: 
          { /* ignore */
          }
        case 37: break;
        case 17: 
          { string.append('\t');
          }
        case 38: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
